Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\staticfiles\storage.py", line 173, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\staticfiles\storage.py", line 152, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\staticfiles\storage.py", line 472, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'tours/style.css'
Not Found: /js/jquery.js
Not Found: /destination/8/js/jquery.js
Not Found: /images/wendy-winarno-timeiBVLB8E-unsplash.jpg
Not Found: /images/Candi_Hindu_Prambanan_BtPlKb7.jpg
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 50, in get_queryset
    user_city = self.get_ip()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 26, in get_ip
    city = g.city(ip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\gis\geoip2\base.py", line 181, in city
    return City(self._city.city(enc_query))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 150, in city
    return cast(City, self._model_for(geoip2.models.City, "City", ip_address))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 253, in _model_for
    (record, prefix_len) = self._get(types, ip_address)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 127.0.0.1 is not in the database.
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 50, in get_queryset
    user_city = self.get_ip()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 26, in get_ip
    city = g.city(ip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\gis\geoip2\base.py", line 181, in city
    return City(self._city.city(enc_query))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 150, in city
    return cast(City, self._model_for(geoip2.models.City, "City", ip_address))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 253, in _model_for
    (record, prefix_len) = self._get(types, ip_address)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 127.0.0.1 is not in the database.
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /images/wisata-candi-prambanan-1-l.jpg
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /favicon.ico
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 193, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Internal Server Error: /admin/tours/city/Yogyakarta/change/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "tours_destination_album_id_key"
DETAIL:  Key (album_id)=(7) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1893, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1750, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1803, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1253, in save_related
    self.save_formset(request, form, formset, change=change)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1241, in save_formset
    formset.save()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 790, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 950, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 1148, in save_new
    return super().save_new(form, commit=commit)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 763, in save_new
    return form.save(commit=commit)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 548, in save
    self.instance.save()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "tours_destination_album_id_key"
DETAIL:  Key (album_id)=(7) already exists.

Internal Server Error: /admin/tours/city/Yogyakarta/change/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "tours_destination_album_id_key"
DETAIL:  Key (album_id)=(7) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1893, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1750, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1803, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1253, in save_related
    self.save_formset(request, form, formset, change=change)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\admin\options.py", line 1241, in save_formset
    formset.save()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 790, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 950, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 1148, in save_new
    return super().save_new(form, commit=commit)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 763, in save_new
    return form.save(commit=commit)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\forms\models.py", line 548, in save
    self.instance.save()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "tours_destination_album_id_key"
DETAIL:  Key (album_id)=(7) already exists.

Not Found: /js/jquery.js
Not Found: /destination/14/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 143, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 128, in rencanaDestinasi
    des = list(filter(lambda x: x.opening_hours < start_time.time() and x.closing_hours > end_time.time(),
IndexError: list index out of range
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 145, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 130, in rencanaDestinasi
    des = list(filter(lambda x: x.opening_hours < start_time.time() and x.closing_hours > end_time.time(),
IndexError: list index out of range
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 147, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 133, in rencanaDestinasi
    des = list(res)[0]
IndexError: list index out of range
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 148, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 134, in rencanaDestinasi
    des = list(res)[0]
IndexError: list index out of range
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 148, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 134, in rencanaDestinasi
    des = list(res)[0]
IndexError: list index out of range
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 146, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 132, in rencanaDestinasi
    des = list(res)[0]
IndexError: list index out of range
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 146, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 132, in rencanaDestinasi
    des = list(res)[0]
IndexError: list index out of range
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 146, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 132, in rencanaDestinasi
    des = list(res)[0]
IndexError: list index out of range
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 146, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 132, in rencanaDestinasi
    des = list(res)[0]
IndexError: list index out of range
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 146, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 131, in rencanaDestinasi
    if res[0] != None:
IndexError: list index out of range
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 146, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 131, in rencanaDestinasi
    if res[0] != None:
IndexError: list index out of range
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 143, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 129, in rencanaDestinasi
    des = res[0]
IndexError: list index out of range
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 144, in get_context_data
    context['plan'] = self.rencanaDestinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 135, in rencanaDestinasi
    destinasi.remove(des)
ValueError: list.remove(x): x not in list
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '['day']' from 'destination_plan['day']'
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 24: 'display', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 24: 'display', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 145, in get_context_data
    context['start'] = self.rencanaDestinasi()['start']
KeyError: 'start'
Not Found: /favicon.ico
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''day'' from 'plan.'day''
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 193, in render
    values = list(values)
TypeError: 'int' object is not iterable
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 145, in get_context_data
    context['destinasi'] = self.rencanaDestinasi()['destinasi']
KeyError: 'destinasi'
Not Found: /js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /js/jquery.js
Not Found: /destination/8/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Not Found: /js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Not Found: /plan/1/js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\multiforloop\templatetags\multifor.py", line 118, in render
    return nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
AttributeError: 'str' object has no attribute 'render_annotated'
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /js/jquery.js
Not Found: /destination/8/js/jquery.js
Not Found: /js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /js/jquery.js
Not Found: /destination/12/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 226, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 3. 
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 226, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 3. 
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 226, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 3. 
Internal Server Error: /plan/1/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 226, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 3. 
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /plan/1/js/jquery.js
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 53, in get_queryset
    user_city = self.get_ip()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 29, in get_ip
    city = g.city(ip) #cari kota based on ip
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\gis\geoip2\base.py", line 181, in city
    return City(self._city.city(enc_query))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 150, in city
    return cast(City, self._model_for(geoip2.models.City, "City", ip_address))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 253, in _model_for
    (record, prefix_len) = self._get(types, ip_address)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 127.0.0.1 is not in the database.
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 53, in get_queryset
    user_city = self.get_ip()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 29, in get_ip
    city = g.city(ip) #cari kota based on ip
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\contrib\gis\geoip2\base.py", line 181, in city
    return City(self._city.city(enc_query))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 150, in city
    return cast(City, self._model_for(geoip2.models.City, "City", ip_address))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 253, in _model_for
    (record, prefix_len) = self._get(types, ip_address)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\geoip2\database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 127.0.0.1 is not in the database.
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\http\request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Bad Request: /HTTP_X_FORWARDED_FOR
Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\http\request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Bad Request: /HTTP_X_FORWARDED_FOR
Not Found: /HTTP_X_FORWARDED_FOR
Internal Server Error: /destination
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 157, in get_queryset
    filter  = self.cari_destinasi()
  File "C:\Users\richo\PycharmProjects\tourmate\tours\views.py", line 154, in cari_destinasi
    return Destination.objects.filter(name__contains=keyword)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\db\models\sql\query.py", line 1308, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /favicon.ico
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /destination/js/jquery.js
Internal Server Error: /destination/
Traceback (most recent call last):
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\richo\PycharmProjects\tourmate\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail' with arguments '('',)' not found. 1 pattern(s) tried: ['destination/(?P<pk>[0-9]+)/\\Z']
Not Found: /destination/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /destination/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /destination/2/js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /destination/8/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /tours/assets/img-sub.png
Not Found: /js/jquery.js
Not Found: /tours/assets/img-sub.png
Not Found: /js/jquery.js
Not Found: /tours/assets/img-sub.png
Not Found: /js/jquery.js
Not Found: /assets/img-sub.png
Not Found: /js/jquery.js
Not Found: /assets/img-sub.png
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /destination/2/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /destination/13/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /favicon.ico
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /destination/8/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /plan/1/js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
Not Found: /js/jquery.js
